import { Widgets } from "@mui/icons-material";

export const columns = [
	{
		field: "id",
		headerName: "ID",
		headerAlign: "center",
		align: "center",
		paddingLeft: 20,
		width: 100,
	},
	{ field: "registrarId", headerName: "Registrar ID", flex: 1 },
	{
		field: "name",
		headerName: "Name",
		cellClassName: "name-column--cell",
		flex: 1
	},
	{
		field: "age",
		headerName: "Age",
		type: "number",
		headerAlign: "left",
		align: "left",
		width: 50,
	},
	{
		field: "phone",
		headerName: "Phone Number",
		flex: 1
	},
	{
		field: "email",
		headerName: "Email",
		flex: 1
	},
	{
		field: "address",
		headerName: "Address",
		flex: 1
	},
	{
		field: "city",
		headerName: "City",
		flex: 1
	},
	{
		field: "zipCode",
		headerName: "Zip Code",
		flex: 1
	},
];

export const rows = [
	{
		id: 1,
		name: "Manuel Rodriguez",
		email: "Mojamed@gmail.com",
		age: 35,
		phone: "972 59-786-7603",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "10001",
		registrarId: 123512,
	},
	{
		id: 2,
		name: "Pablo",
		email: "Pablo@gmail.com",
		age: 42,
		phone: "+624 59-854-8459",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "13151",
		registrarId: 123512,
	},
	{
		id: 3,
		name: "Matias",
		email: "matias@gmail.com",
		age: 45,
		phone: "+624 59-854-8958",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "87281",
		registrarId: 4132513,
	},
	{
		id: 4,
		name: "Abd",
		email: "abd@gmail.com",
		age: 16,
		phone: "(921)425-6742",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "15551",
		registrarId: 123512,
	},
	{
		id: 5,
		name: "Amal",
		email: "amal@gmail.com",
		age: 31,
		phone: "(421)445-1189",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "14215",
		registrarId: 123512,
	},
	{
		id: 6,
		name: "Noha",
		email: "noho@gmail.com",
		age: 78,
		phone: "(232)545-6483",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "10001",
		registrarId: 123512,
	},
	{
		id: 7,
		name: "Nahuel",
		email: "Nahuel@gmail.com",
		age: 44,
		phone: "(543)124-0123",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "51523",
		registrarId: 123512,
	},
	{
		id: 8,
		name: "Rafael",
		email: "Rafael@gmail.com",
		age: 36,
		phone: "(222)444-5555",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "44215",
		registrarId: 512315,
	},
	{
		id: 9,
		name: "Anas",
		email: "anas@gmail.com",
		age: 65,
		phone: "(444)555-6239",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "111234",
		registrarId: 928397,
	},
	{
		id: 10,
		name: "Ramiro",
		email: "ramiro@gmail.com",
		age: 42,
		phone: "(222)444-5555",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "44215",
		registrarId: 533215,
	},
	{
		id: 11,
		name: "Nicolas",
		email: "Nicolas@gmail.com",
		age: 11,
		phone: "(444)555-6239",
		address: "Cangas - Galicia",
		city: "Cangas",
		zipCode: "1234",
		registrarId: 92197,
	},
];
